# Generated by Django 4.0.3 on 2022-03-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="type",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "Other"),
                    (
                        "Commercial",
                        (
                            (100, "Commercial (generic)"),
                            (101, "Internet Provider"),
                            (102, "Internet Exchange"),
                        ),
                    ),
                    (
                        "Non-Profit",
                        (
                            (200, "Non-Profit (generic)"),
                            (201, "Association"),
                            (202, "Foundation"),
                        ),
                    ),
                    (
                        "Governmental",
                        ((900, "Government (generic)"), (901, "Regulator")),
                    ),
                ],
                default=0,
                verbose_name="type",
            ),
        ),
    ]
