# Generated by Django 4.0.3 on 2022-03-18 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contact_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='is_staff',
        ),
    ]
