# Generated by Django 4.0.3 on 2022-03-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0006_remove_contact_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="listed",
            field=models.BooleanField(
                default=False,
                help_text="Shown as a personal donor on the website",
                verbose_name="listed",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="listed",
            field=models.BooleanField(
                default=False,
                help_text="Shown as a donor organisation on the website",
                verbose_name="listed",
            ),
        ),
    ]
