# Generated by Django 4.0.3 on 2022-03-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_contact_listed_organisation_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='logo'),
        ),
    ]
