# Generated by Django 4.0.3 on 2022-04-02 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0008_organisation_logo"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="contact",
            managers=[],
        ),
    ]
