# Generated by Django 4.0.3 on 2022-04-04 23:39

import contacts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0009_alter_contact_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="contact",
            managers=[
                ("objects", contacts.models.ContactManager()),
            ],
        ),
    ]
