# Generated by Django 4.0.3 on 2023-02-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_contact_requested_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='allow_publicity',
            field=models.BooleanField(default=False, help_text='Shown as a personal donor in articles, presentations etc.', verbose_name='allow publicity'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='allow_publicity',
            field=models.BooleanField(default=False, help_text='Shown as a donor organisation in articles, presentations etc.', verbose_name='allow publicity'),
        ),
    ]
