# Generated by Django 4.0.3 on 2023-01-02 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_contact_requested_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_through',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='contacted through'),
        ),
    ]
