# Generated by Django 4.0.3 on 2023-02-13 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_contact_contact_through'),
        ('contacts', '0014_alter_contact_allow_publicity_alter_contact_listed_and_more'),
    ]

    operations = [
    ]
