# Generated by Django 4.0.3 on 2022-04-20 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_claim_when'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'verbose_name': 'claim', 'verbose_name_plural': 'claims'},
        ),
    ]
