# Generated by Django 4.0.3 on 2022-04-21 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_claim_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='when',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='when'),
        ),
    ]
