# Generated by Django 4.0.3 on 2022-04-21 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='logistics.location', verbose_name='current location'),
        ),
    ]
