# Generated by Django 4.0.3 on 2022-04-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0007_default_locations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="when",
            field=models.DateField(auto_now_add=True, verbose_name="when"),
        ),
    ]
