# Generated by Django 4.0.3 on 2022-07-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_location_email_location_is_collection_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='is_collection_point',
            field=models.BooleanField(default=False, help_text='allow donors to send equipment to this location', verbose_name='is a collection point'),
        ),
    ]
