# Generated by Django 4.0.3 on 2022-07-04 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0016_equipmentdata'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipmentdata',
            unique_together={('brand', 'model')},
        ),
    ]
