# Generated by Django 4.0.7 on 2022-09-15 07:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supply_demand', '0029_requestitem_offered_items'),
        ('logistics', '0019_alter_equipmentdata_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, help_text='The amount of items claimed', verbose_name='amount')),
                ('when', models.DateField(verbose_name='when')),
                ('created_at', models.DateTimeField(verbose_name='created at')),
                ('updated_at', models.DateTimeField(verbose_name='updated at')),
                ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.location', verbose_name='current location')),
                ('offered_item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='supply_demand.offeritem', verbose_name='offered item')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.shipment', verbose_name='shipment')),
            ],
            options={
                'verbose_name': 'shipment item',
                'verbose_name_plural': 'shipment items',
            },
        ),
    ]
