# Generated by Django 4.0.7 on 2022-09-15 07:08

from django.db import migrations


def fill_shipment_item(apps, schema_editor):
    Claim = apps.get_model("logistics", "Claim")
    ShipmentItem = apps.get_model("logistics", "ShipmentItem")
    Shipment = apps.get_model("logistics", "Shipment")

    for item in Claim.objects.all().select_related("offered_item", "requested_item"):
        if not item.shipment:
            continue
        ShipmentItem.objects.create(
            shipment=item.shipment,
            claim=item,
            amount=item.amount,
            when=item.when,
            current_location=item.current_location,
            created_at=item.when,
            updated_at=item.when
        )

    for item in Shipment.objects.all():
        if item.when:
            item.updated_at = item.when
            item.created_at = item.when
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0020_shipment_created_at_shipment_updated_at_shipmentitem'),
    ]

    operations = [
        migrations.RunPython(fill_shipment_item),
    ]
