# Generated by Django 4.0.7 on 2022-09-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0021_auto_20220915_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='when',
            field=models.DateField(auto_now_add=True, verbose_name='when'),
        ),
    ]
