# Generated by Django 4.0.7 on 2022-09-15 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_demand', '0029_requestitem_offered_items'),
        ('logistics', '0022_alter_shipment_created_at_alter_shipment_updated_at_and_more'),
    ]

    operations = [
        # migrations.SeparateDatabaseAndState(
        #     state_operations=[
        #         migrations.DeleteModel(
        #             name="Claim",
        #         ),
        #     ],
        #     database_operations=[],
        # )
    ]
