# Generated by Django 4.0.7 on 2022-09-17 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0023_delete_claim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='shipmentitem',
            name='current_location',
        ),
        migrations.AddField(
            model_name='shipment',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='from_location', to='logistics.location', verbose_name='from location'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='to_location', to='logistics.location', verbose_name='to location'),
        ),
        migrations.AlterField(
            model_name='ShipmentItem',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='supply_demand.claim', verbose_name='claimed item'),
        ),
    ]
