# Generated by Django 4.0.7 on 2022-09-28 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0026_shipmentitem_last_location'),
    ]

    operations = [
    ]
