# Generated by Django 4.0.7 on 2022-09-29 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0027_auto_20220928_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentitem',
            name='parent_shipment_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.shipmentitem', verbose_name='parent shipment item'),
        ),
    ]
