# Generated by Django 4.0.7 on 2022-10-09 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0028_shipmentitem_parent_shipment_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
            ],
            options={
                'verbose_name': 'available item',
                'verbose_name_plural': 'available items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('logistics.shipmentitem',),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='parent_shipment_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_items', to='logistics.shipmentitem', verbose_name='parent shipment item'),
        ),
    ]
