# Generated by Django 4.0.7 on 2022-10-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0029_item_alter_shipmentitem_parent_shipment_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='when',
            new_name='delivery_date',
        ),
        migrations.AddField(
            model_name='shipment',
            name='notes',
            field=models.TextField(blank=True, help_text='Provide details on this shipment', verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_date',
            field=models.DateField(blank=True, null=True, verbose_name='shipment date'),
        ),
    ]
