# Generated by Django 4.0.7 on 2022-10-18 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0030_remove_shipment_when_shipment_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='delivery date'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='amount',
            field=models.PositiveIntegerField(default=1, help_text='The amount of items claimed', validators=[django.core.validators.MinValueValidator(1)], verbose_name='amount'),
        ),
    ]
