# Generated by Django 4.0.7 on 2022-10-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0031_alter_shipment_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Donor'), (2, 'Collection point'), (3, 'Distribution point'), (4, 'Requester')], default=2, verbose_name='type'),
        ),
    ]
