# Generated by Django 4.0.7 on 2022-10-18 16:45

from django.db import migrations


def location_type(apps, schema_editor):
    Location = apps.get_model("logistics", "Location")

    for location in Location.objects.all():
        if location.is_collection_point:
            value = 2
        elif location.is_distribution_point:
            value = 3
        elif "donor" in location.name.lower():
            value = 1
        else:
            value = 4
        location.type = value
        location.save()


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0032_location_type'),
    ]

    operations = [
        migrations.RunPython(location_type),
    ]
