# Generated by Django 4.0.7 on 2022-10-18 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0033_auto_20221018_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='is_collection_point',
        ),
        migrations.RemoveField(
            model_name='location',
            name='is_distribution_point',
        ),
    ]
