# Generated by Django 4.0.3 on 2022-10-24 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0034_remove_location_is_collection_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentitem',
            name='parent_shipment_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_items', to='logistics.shipmentitem', verbose_name='parent shipment item'),
        ),
    ]
