# Generated by Django 4.0.3 on 2022-11-14 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply_demand', '0032_remove_claim_current_location_remove_claim_shipment'),
        ('logistics', '0035_alter_shipmentitem_parent_shipment_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'shipment history', 'verbose_name_plural': 'history of shipments'},
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='supply_demand.claim', verbose_name='claim'),
        ),
    ]
