# Generated by Django 4.0.3 on 2022-11-16 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0036_alter_item_options_alter_shipmentitem_claim'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Claim",
                ),
            ],
            database_operations=[],
        )
    ]
