# Generated by Django 4.0.3 on 2022-11-20 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0037_delete_claim'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'shipment item', 'verbose_name_plural': 'shipping logistics'},
        ),
    ]
