# Generated by Django 4.0.3 on 2022-11-27 15:10

from django.db import migrations


def fill_shipment_item(apps, schema_editor):
    ShipmentItem = apps.get_model("logistics", "ShipmentItem")

    for item in ShipmentItem.objects.all().select_related("offered_item"):
        item.offered_item_id = item.claim_tmp.offered_item_id
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0039_rename_claim_shipmentitem_claim_tmp_and_more'),
    ]

    operations = [
        migrations.RunPython(fill_shipment_item),
    ]
