# Generated by Django 4.0.3 on 2022-11-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0041_remove_shipmentitem_claim_tmp'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'On the Way'), (3, 'Delivered')], default=1, verbose_name='status'),
            preserve_default=False,
        ),
    ]
