# Generated by Django 4.0.3 on 2022-11-29 09:09

from django.db import migrations


def fill_shipment_status(apps, schema_editor):
    Shipment = apps.get_model("logistics", "Shipment")

    for item in Shipment.objects.all():
        if item.is_delivered:
            item.status = 3
        else:
            item.status = 1
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0042_shipment_status'),
    ]

    operations = [
        migrations.RunPython(fill_shipment_status),
    ]
