# Generated by Django 4.0.3 on 2022-11-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0043_auto_20221129_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='is_delivered',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'On the Way'), (3, 'Delivered')], default=1, verbose_name='status'),
        ),
    ]
