# Generated by Django 4.0.3 on 2022-12-03 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0045_auto_20221202_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentitem',
            name='when',
        ),
    ]
