stages:
  - deploy

deploy-job:
  stage: deploy
  script:
    - mkdir -p "$HOME/private/ci/$CI_COMMIT_BRANCH"
    - rsync -av --delete \
        --exclude .git \
        --exclude static \
        --exclude media \
        --exclude aid_coordinator/local_settings.py
        ./ "$HOME/private/ci/$CI_COMMIT_BRANCH"
    - cd "$HOME/private/ci/$CI_COMMIT_BRANCH"
    - poetry install
    - poetry run ./manage.py migrate --no-input
    - poetry run ./manage.py --no-input
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
  tags:
    - kuc
