# Generated by Django 4.0.3 on 2022-03-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_demand", "0002_offer_alter_request_options_offeritem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offer",
            options={
                "ordering": ("organisation__name",),
                "verbose_name": "offer",
                "verbose_name_plural": "offers",
            },
        ),
        migrations.AlterField(
            model_name="offeritem",
            name="brand",
            field=models.CharField(max_length=50, verbose_name="brand"),
        ),
        migrations.AlterField(
            model_name="offeritem",
            name="model",
            field=models.CharField(max_length=50, verbose_name="model"),
        ),
    ]
