# Generated by Django 4.0.3 on 2022-03-18 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_demand', '0006_offeritem_claimed_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ('description',), 'verbose_name': 'offer', 'verbose_name_plural': 'offers'},
        ),
    ]
