# Generated by Django 4.0.3 on 2022-03-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_demand", "0008_alter_offer_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offeritem",
            name="brand",
            field=models.CharField(blank=True, max_length=50, verbose_name="brand"),
        ),
    ]
