# Generated by Django 4.0.3 on 2022-03-18 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0005_alter_contact_organisation'),
        ('supply_demand', '0009_alter_offeritem_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='offers', to=settings.AUTH_USER_MODEL, verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='offers', to='contacts.organisation', verbose_name='organisation'),
        ),
        migrations.AlterField(
            model_name='offeritem',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_items', to=settings.AUTH_USER_MODEL, verbose_name='claimed by'),
        ),
        migrations.AlterField(
            model_name='offeritem',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='supply_demand.offer', verbose_name='offer'),
        ),
        migrations.AlterField(
            model_name='request',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='request',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='requests', to='contacts.organisation', verbose_name='organisation'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='alternative_for',
            field=models.ForeignKey(blank=True, help_text='In case there are multiple options to solve your problem', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='supply_demand.requestitem', verbose_name='alternative for'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='supply_demand.request', verbose_name='request'),
        ),
    ]
