# Generated by Django 4.0.3 on 2022-03-18 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_demand', '0010_alter_offer_contact_alter_offer_organisation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ('description', 'contact__organisation__name', 'contact__first_name', 'contact__last_name'), 'verbose_name': 'offer', 'verbose_name_plural': 'offers'},
        ),
        migrations.RemoveField(
            model_name='offer',
            name='organisation',
        ),
    ]
