# Generated by Django 4.0.3 on 2022-04-04 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supply_demand", "0021_alter_offer_unused_item_handling"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="change",
            managers=[],
        ),
    ]
