# Generated by Django 4.0.3 on 2022-04-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_demand', '0027_alter_offeritem_model_alter_requestitem_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeritem',
            name='rejected',
            field=models.BooleanField(default=False, verbose_name='rejected'),
        ),
    ]
