# Generated by Django 4.0.7 on 2022-09-05 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_demand', '0028_offeritem_rejected'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offeritem',
            options={'ordering': ('type', 'brand', 'model'), 'permissions': (('view_own_offeritem', 'Can view own offer item'), ('change_own_offeritem', 'Can change own offer item'), ('delete_own_offeritem', 'Can delete own offer item')), 'verbose_name': 'offered item', 'verbose_name_plural': 'offered items'},
        ),
        migrations.AlterModelOptions(
            name='requestitem',
            options={'ordering': ('type', 'brand', 'model'), 'permissions': (('view_own_requestitem', 'Can view own request item'), ('change_own_requestitem', 'Can change own request item'), ('delete_own_requestitem', 'Can delete own request item')), 'verbose_name': 'requested item', 'verbose_name_plural': 'requested items'},
        ),
    ]
