# Generated by Django 4.0.3 on 2022-11-27 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply_demand', '0028_offeritem_rejected'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('order', models.PositiveIntegerField(verbose_name='order')),
            ],
            options={
                'verbose_name': 'item type',
                'verbose_name_plural': 'item types',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.RenameField(
            model_name='offeritem',
            old_name='type',
            new_name='old_type',
        ),
        migrations.RenameField(
            model_name='requestitem',
            old_name='type',
            new_name='old_type',
        ),
        migrations.AddField(
            model_name='offeritem',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='supply_demand.itemtype', verbose_name='type'),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='supply_demand.itemtype', verbose_name='type'),
        ),
    ]
