# Generated by Django 4.0.3 on 2022-11-27 18:46

from django.db import migrations


# noinspection PyPep8Naming
def migrate_type(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    ItemType = apps.get_model('supply_demand', 'ItemType')
    OfferItem = apps.get_model('supply_demand', 'OfferItem')
    RequestItem = apps.get_model('supply_demand', 'RequestItem')

    # First make sure the old types exist
    other, _ = ItemType.objects.using(db_alias).get_or_create(defaults={'order': 100}, name='Other')
    hardware, _ = ItemType.objects.using(db_alias).get_or_create(defaults={'order': 50}, name='Hardware')
    software, _ = ItemType.objects.using(db_alias).get_or_create(defaults={'order': 50}, name='Software')
    service, _ = ItemType.objects.using(db_alias).get_or_create(defaults={'order': 50}, name='Service')

    # Update items
    OfferItem.objects.using(db_alias).filter(old_type=0).update(type=other)
    RequestItem.objects.using(db_alias).filter(old_type=0).update(type=other)

    OfferItem.objects.using(db_alias).filter(old_type=100).update(type=hardware)
    RequestItem.objects.using(db_alias).filter(old_type=100).update(type=hardware)

    OfferItem.objects.using(db_alias).filter(old_type=200).update(type=software)
    RequestItem.objects.using(db_alias).filter(old_type=200).update(type=software)

    OfferItem.objects.using(db_alias).filter(old_type=300).update(type=service)
    RequestItem.objects.using(db_alias).filter(old_type=300).update(type=service)


class Migration(migrations.Migration):
    dependencies = [
        ('supply_demand', '0029_itemtype_offeritem_old_type_requestitem_old_type_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_type),
    ]
