# Generated by Django 4.0.7 on 2022-09-15 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0023_delete_claim'),
        ('supply_demand', '0029_requestitem_offered_items'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Claim',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('amount', models.PositiveIntegerField(default=1, help_text='The amount of items claimed', verbose_name='amount')),
                        ('when', models.DateField(auto_now_add=True, verbose_name='when')),
                        ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.location', verbose_name='current location')),
                        ('offered_item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='supply_demand.offeritem', verbose_name='offered item')),
                    ],
                    options={
                        'verbose_name': 'claim',
                        'verbose_name_plural': 'claims',
                        'db_table': 'logistics_claim',
                    },
                ),
                migrations.AlterField(
                    model_name='requestitem',
                    name='offered_items',
                    field=models.ManyToManyField(related_name='requested_items', through='supply_demand.Claim', to='supply_demand.offeritem'),
                ),
                migrations.AddField(
                    model_name='claim',
                    name='requested_item',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supply_demand.requestitem', verbose_name='requested item'),
                ),
                migrations.AddField(
                    model_name='claim',
                    name='shipment',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.shipment', verbose_name='shipment'),
                ),
            ],
            database_operations=[],
        )
    ]
