# Generated by Django 4.0.7 on 2022-09-15 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_demand', '0030_claim_alter_requestitem_offered_items_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='claim',
            table=None,
        ),
    ]
