# Generated by Django 4.0.3 on 2022-11-27 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply_demand', '0030_type_migrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offeritem',
            name='old_type',
        ),
        migrations.RemoveField(
            model_name='requestitem',
            name='old_type',
        ),
        migrations.AlterField(
            model_name='offeritem',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='supply_demand.itemtype', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='supply_demand.itemtype', verbose_name='type'),
        ),
    ]
