# Generated by Django 4.0.3 on 2022-11-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_demand', '0032_alter_itemtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='order',
            field=models.PositiveIntegerField(default=50, verbose_name='order'),
        ),
    ]
