# Generated by Django 4.0.3 on 2022-11-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_demand', '0032_remove_claim_current_location_remove_claim_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='notes',
            field=models.TextField(blank=True, help_text='Any extra information related to claim', verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='claim',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
