# Generated by Django 4.0.7 on 2022-10-09 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0029_item_alter_shipmentitem_parent_shipment_item'),
        ('supply_demand', '0032_remove_claim_current_location_remove_claim_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='shipment_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.shipmentitem', verbose_name='shipment item'),
        ),
    ]
