# Generated by Django 4.0.3 on 2022-11-27 15:11

from django.db import migrations


def fill_claim_shipmentitem(apps, schema_editor):
    Claim = apps.get_model("supply_demand", "Claim")

    for item in Claim.objects.all().prefetch_related("shipmentitem_set"):
        item.shipment_item_id = item.shipmentitem_set.first()
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('supply_demand', '0034_claim_created_at_claim_shipment_item'),
    ]

    operations = [
        migrations.RunPython(fill_claim_shipmentitem),
    ]
