# Generated by Django 4.0.3 on 2022-11-27 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_demand', '0033_alter_itemtype_order'),
        ('supply_demand', '0035_auto_20221127_1511'),
    ]

    operations = [
    ]
