# Generated by Django 4.0.3 on 2022-12-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_demand', '0036_merge_20221127_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offeritem',
            name='received',
        ),
    ]
