# Generated by Django 4.0.3 on 2022-12-03 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_demand', '0037_remove_offeritem_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='shipment_item',
        ),
    ]
