# Generated by Django 4.0.3 on 2022-12-04 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply_demand', '0038_remove_claim_shipment_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='requested_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='supply_demand.requestitem', verbose_name='requested item'),
        ),
    ]
