# Generated by Django 4.0.3 on 2023-01-05 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0047_shipment_parent_shipment_alter_shipmentitem_shipment'),
        ('supply_demand', '0039_alter_claim_requested_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeritem',
            name='equipment_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.equipmentdata', verbose_name='offer'),
        ),
    ]
